home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('services/', views.services, name='services'),
    path('pricing/', views.pricing, name='pricing'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('company/admin/', views.admin, name='admin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('productadd/', views.productadd, name='productadd'),
    path('categoryadd/', views.categoryadd, name='categoryadd'),
    path('products', views.products, name='products'),
    path('categories', views.categories, name='categories'),
    path('product/<int:product_id>/edit/', views.editproduct, name='editproduct'),
]

login/urls.py
from django.urls import path , include

from .views import *
app_name = "login"

urlpatterns = [
    path('giris/', login_view, name='login'),
    path('kayit/ol/', register_view, name="register"),
    path('cikis/', logout_view, name="logout")
]

qr/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('kullanici/', include('login.urls')),
]

home/models.py
from django.db import models

# Create your models here.

class About(models.Model):
    company = models.CharField(max_length=30)
    content = models.TextField()
    about_image = models.CharField(max_length=250)

    def __str__(self):
        return self.company

class GalleryType(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

class Gallery(models.Model):
    is_active = models.BooleanField(default=True)
    category = models.ManyToManyField(GalleryType)
    image = models.TextField(max_length=250)    
    image_name = models.CharField(max_length=30)

    def __str__(self):
        return self.image_name
    
class Reference(models.Model):
    name = models.CharField(max_length=30)
    image = models.TextField(max_length=250)

    def __str__(self):
        return self.name    
    
class Planing(models.Model):
    title = models.CharField(max_length=30)
    property1 = models.CharField(max_length=250)
    property2 = models.CharField(max_length=250)
    property3 = models.CharField(max_length=250)
    property4 = models.CharField(max_length=250)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
class Services(models.Model):
    name = models.CharField(max_length=50, default="Services")
    title1 = models.CharField(max_length=50)
    content1 = models.TextField()
    title2 = models.CharField(max_length=50)
    content2 = models.TextField()
    title3 = models.CharField(max_length=50)
    content3 = models.TextField()

    def __str__(self):
        return self.name 

home/forms.py
from django import forms
from apps.product.models import Product, Category  # your app's models import

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import About , GalleryType, Gallery, Reference, Planing, Services
from .forms import ProductForm, CategoryForm
from apps.product.models import Category, Product, ProductImage

# Create your views here.
def index(request):
    abouts = About.objects.first()
    galeri_names = GalleryType.objects.all()
    galeris = Gallery.objects.filter(is_active=True)
    category= Gallery.objects.filter(is_active=True)
    references = Reference.objects.all()

    return render(request, 'index.html', {'abouts': abouts, 'name': galeri_names, 'galeris': galeris, 'category': category, 'reference': references })

def services(request):
    service = Services.objects.first()

    return render(request, 'services.html', {'service': service})

def pricing(request):
    plans = Planing.objects.filter(is_active=True)

    return render(request, 'pricing.html', {'plans': plans})

def login(request):
    return render(request, 'login.html')

def register(request):
    return render(request, 'register.html')

def admin(request):
  context = {
    'segment'  : 'index',
  }
  return render(request, "admin/pages/index.html", context)

def dashboard(request):
  return render(request, "admin/pages/index.html")


def productadd(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()  # Formu kaydet
            return redirect('products')  # İşlem başarılıysa yönlendirme
    else:
        form = ProductForm()

    return render(request, 'admin/pages/productadd.html', {'form': form})

def categoryadd(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()  # Formu kaydet
            return redirect('categories')  # İşlem başarılıysa yönlendirme
    else:
        form = CategoryForm()

    return render(request, 'admin/pages/categoryadd.html', {'form': form})

def products(request):
    products = Product.objects.filter(is_active=True)

    return render(request, 'admin/pages/products.html', {'products': products})

def categories(request):
    categories = Category.objects.filter(is_active=True)

    return render(request, 'admin/pages/categories.html', {'categories': categories})

def editproduct(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    # Düzenleme ekranını göstermek için product objesini şablonla birleştirin ve gönderin.
    return render(request, 'admin/pages/editproduct.html', {'product': product})

home/templates/partials/_about.html
{% load static %}
<div id="about">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h2>Minimax Story</h2>
			</div>
			<div class="col-md-6 col-sm-6">
				<img src="{{ abouts.about_image }}">
			</div>
			<div class="col-md-6 col-sm-6">
				<h3>ABOUT US</h3>
				<h4>{{ abouts.company }}</h4>
				<p>{{ abouts.content }}</p>
			</div>
		</div>
	</div>
</div>

home/templates/partials/_contact.html
<div id="contact">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h2>Keep in touch</h2>
			</div>
			<form action="#" method="post" role="form">
				<div class="col-md-1 col-sm-1"></div>
				<div class="col-md-10 col-sm-10">
					<div class="col-md-6 col-sm-6">
						<input name="name" type="text" class="form-control" id="name" placeholder="Name">
				  	</div>
					<div class="col-md-6 col-sm-6">
						<input name="email" type="email" class="form-control" id="email" placeholder="Email">
				  	</div>
                    <div class="col-md-12 col-sm-12">
						<input name="subject" type="text" class="form-control" id="subject" placeholder="Subject">
	    	  	  	</div>
					<div class="col-md-12 col-sm-12">
						<textarea name="message" rows="5" class="form-control" id="message" placeholder="Message"></textarea>
					</div>
					<div class="col-md-8 col-sm-8">
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy</p>
					</div>
					<div class="col-md-4 col-sm-4">
						<input name="submit" type="submit" class="form-control" id="submit" value="SEND MESSAGE">
					</div>
				</div>
				<div class="col-md-1 col-sm-1"></div>
			</form>
		</div>
	</div>
</div>

home/templates/partials/_divider.html
<div class="container">
	<div class="row">
		<div class="col-md-12 col-sm-12">
			<hr>
		</div>
	</div>
</div>

home/templates/partials/_footer.html
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-6">
				<h2>Our Office</h2>
				<p>Adres: {{ADDRESS}}</p>
				<p>Email: <span>{{EMAIL}}</span></p>
				<p>Phone: <span>{{NUMBER}}</span></p>
			</div>
			<div class="col-md-6 col-sm-6">
				<h2>Social Us</h2>
				<ul class="social-icons">
					{% if INSTAGRAM %}
					<li><a href="{{INSTAGRAM}}" target="_blank" class="fa fa-instagram"></a></li>
					{% endif %}
					{% if FACEBOOK %}
					<li><a href="{{FACEBOOK}}" target="_blank" class="fa fa-facebook"></a></li>
					{% endif %}
					{% if TWITTER %}
					<li><a href="{{TWITTER}}" target="_blank" class="fa fa-twitter"></a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
</footer>
<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<p>Copyright &copy; 2016 Minimax Digital Firm 
                
                - Design: <a rel="nofollow" href="http://www.tooplate.com" target="_parent">Tooplate</a></p>
			</div>
		</div>
	</div>
</div>

home/templates/partials/_head.html
{% load static %}
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<title>Minimax HTML5 Free Template</title>
<!--

Template 2080 Minimax

http://www.tooplate.com/view/2080-minimax

-->
	<!-- stylesheet css -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/nivo-lightbox.css' %}">
	<link rel="stylesheet" href="{% static 'css/nivo_themes/default/default.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/reference.css' %}">
	<!-- google web font css -->
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600,700' rel='stylesheet' type='text/css'>
</head>

home/templates/partials/_homesec.html
<div id="home">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-6 col-md-6 col-sm-offset-6 col-sm-6">
				<h2>Welcome to</h2>
				<h1>{{SITENAME}} <strong>{{SLOGAN}}</strong></h1>
				<p>{{CONTEXT}}</p>
				<a href="#service" class="btn btn-default smoothScroll">GET STARTED</a>
			</div>
		</div>
	</div>
</div>

home/templates/partials/_js.html
{% load static %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>	
<script src="{% static 'js/nivo-lightbox.min.js' %}"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/jquery.nav.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/imagesloaded.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="{% static 'js/reference.js' %}"></script>

home/templates/partials/_nav.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="{% url 'index' %}" class="navbar-brand smoothScroll">Minimax</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
			  <li {% if request.path == '/' %} class="active" {% endif %}>
				<a href="{% url 'index' %}" class="smoothScroll">ANASAYFA</a>
			  </li>
			  <li {% if request.path == '/pricing/' %} class="active" {% endif %}>
				<a href="{% url 'pricing' %}" class="smoothScroll">FİYATLANDIRMA</a>
			  </li>
			  <li {% if request.path == '/services/' %} class="active" {% endif %}>
				<a href="{% url 'services' %}" class="smoothScroll">HİZMETLER</a>
			  </li>
			  {% if not request.user.is_authenticated %}	
			  <li {% if request.path == '/login/' %} class="active" {% endif %}>
				<a href="{% url 'login:login' %}" class="smoothScroll">GİRİŞ YAP</a>
			  </li>
			  <li {% if request.path == '/register/' %} class="active" {% endif %}>
				<a href="{% url 'login:register' %}" class="smoothScroll">KAYIT OL</a>
			  </li>
			  {% else %}
			  <li>
				<a href="{% url 'login:logout' %}" class="smoothScroll">ÇIKIŞ YAP</a>
			  </li>
			  {% endif %}
			</ul>
		  </div>
	</div>
</div>		

home/templates/partials/_portfolio.html
{% load static %}
<div id="portfolio">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="title">
					<h2>Our Portfolio</h2>
				</div>
				<!-- ISO section -->
				<div class="iso-section">
					<ul class="filter-wrapper clearfix">
                   		 <li><a href="#" data-filter="*" class="selected opc-main-bg">All</a></li>                   	
                   		 {% for names in name %}
                    		<li><a href="#" class="opc-main-bg" data-filter=".{{ names.name }}">{{ names.name }}</a></li>
						 {% endfor %}
               		</ul>
               		<div class="iso-box-section">
               			<div class="iso-box-wrapper col4-iso-box">
							{% for kategori in category %}
								{% if galeris %}
									{% for galeri in galeris %}
										<div class="iso-box {{kategori.name}} col-md-4 col-sm-6 col-xs-12">
											<a href="images/portfolio-img1.jpg" data-lightbox-gallery="portfolio-gallery"><img src="{{ galeri.image }}" alt="portfolio img"></a>
										</div>	
									{% endfor %}
								{% endif %}								
							{% endfor %}

               			</div>
               		</div>
				</div>
			</div>
		</div>
	</div>
</div>		
		

home/templates/partials/_referance.html
{% load static %}
<div class="slider-container">
  <div class="slider">
    {% for references in reference %}
						<a href="images/portfolio-img1.jpg" data-lightbox-gallery="portfolio-gallery" class="me-1"><img src="{{ references.image }}" alt="portfolio img"></a>
		{% endfor %}
  </div>
</div>